from django.core.management.base import BaseCommand
from workouts.models import Exercise

class Command(BaseCommand):
    help = 'Seeds production-ready database of athlete exercises.'

    def handle(self, *args, **options):
        exercises = [
            # --- RUNNER ---
            {"exercise_id": "RUN_001", "exercise_name": "A-Skip Drills", "discipline_category": "Runner", "movement_pattern": "Sprint", "primary_muscle_group": "Hip Flexors", "energy_system": "ATP-PC", "cns_load_score": 3.0, "intensity_type": "Power", "recommended_min_sets": 3, "recommended_max_sets": 5, "recommended_min_reps": 10, "recommended_max_reps": 20, "rest_time_seconds_min": 60, "rest_time_seconds_max": 90, "equipment_required": "Track", "unilateral_or_bilateral": "Unilateral", "complexity_level": "Beginner", "injury_risk_level": "Low"},
            {"exercise_id": "RUN_002", "exercise_name": "Flying 30m Sprints", "discipline_category": "Runner", "movement_pattern": "Sprint", "primary_muscle_group": "Hamstrings", "energy_system": "ATP-PC", "cns_load_score": 9.0, "intensity_type": "Power", "recommended_min_sets": 4, "recommended_max_sets": 8, "recommended_min_reps": 1, "recommended_max_reps": 1, "rest_time_seconds_min": 180, "rest_time_seconds_max": 300, "equipment_required": "Track", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Advanced", "injury_risk_level": "High"},
            {"exercise_id": "RUN_003", "exercise_name": "400m Repeats", "discipline_category": "Runner", "movement_pattern": "Sprint", "primary_muscle_group": "Quadriceps", "energy_system": "Glycolytic", "cns_load_score": 8.5, "intensity_type": "Conditioning", "recommended_min_sets": 4, "recommended_max_sets": 10, "recommended_min_reps": 1, "recommended_max_reps": 1, "rest_time_seconds_min": 120, "rest_time_seconds_max": 240, "equipment_required": "Track", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Intermediate", "injury_risk_level": "Moderate"},
            {"exercise_id": "RUN_004", "exercise_name": "Tempo Run (20min)", "discipline_category": "Runner", "movement_pattern": "Sprint", "primary_muscle_group": "Cardio", "energy_system": "Oxidative", "cns_load_score": 6.5, "intensity_type": "Conditioning", "recommended_min_sets": 1, "recommended_max_sets": 1, "recommended_min_reps": 1, "recommended_max_reps": 1, "rest_time_seconds_min": 300, "rest_time_seconds_max": 300, "equipment_required": "Track", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Beginner", "injury_risk_level": "Low"},
            {"exercise_id": "RUN_005", "exercise_name": "Hill Sprints 50m", "discipline_category": "Runner", "movement_pattern": "Sprint", "primary_muscle_group": "Glutes", "energy_system": "ATP-PC", "cns_load_score": 8.5, "intensity_type": "Power", "recommended_min_sets": 5, "recommended_max_sets": 10, "recommended_min_reps": 1, "recommended_max_reps": 1, "rest_time_seconds_min": 120, "rest_time_seconds_max": 180, "equipment_required": "Track", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Intermediate", "injury_risk_level": "Moderate"},
            # --- JUMPER ---
            {"exercise_id": "JMP_001", "exercise_name": "Depth Jumps", "discipline_category": "Jumper", "movement_pattern": "Jump", "primary_muscle_group": "Calves/Achilles", "energy_system": "ATP-PC", "cns_load_score": 9.5, "intensity_type": "Power", "recommended_min_sets": 3, "recommended_max_sets": 5, "recommended_min_reps": 3, "recommended_max_reps": 5, "rest_time_seconds_min": 120, "rest_time_seconds_max": 240, "equipment_required": "None", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Advanced", "injury_risk_level": "High"},
            {"exercise_id": "JMP_002", "exercise_name": "Single-Leg Box Jumps", "discipline_category": "Jumper", "movement_pattern": "Jump", "primary_muscle_group": "Glutes", "energy_system": "ATP-PC", "cns_load_score": 7.5, "intensity_type": "Power", "recommended_min_sets": 3, "recommended_max_sets": 4, "recommended_min_reps": 4, "recommended_max_reps": 6, "rest_time_seconds_min": 90, "rest_time_seconds_max": 180, "equipment_required": "None", "unilateral_or_bilateral": "Unilateral", "complexity_level": "Intermediate", "injury_risk_level": "Moderate"},
            {"exercise_id": "JMP_003", "exercise_name": "Pogo Hops", "discipline_category": "Jumper", "movement_pattern": "Jump", "primary_muscle_group": "Calves", "energy_system": "ATP-PC", "cns_load_score": 4.0, "intensity_type": "Power", "recommended_min_sets": 2, "recommended_max_sets": 4, "recommended_min_reps": 10, "recommended_max_reps": 20, "rest_time_seconds_min": 60, "rest_time_seconds_max": 90, "equipment_required": "None", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Beginner", "injury_risk_level": "Low"},
            {"exercise_id": "JMP_004", "exercise_name": "Broad Jumps", "discipline_category": "Jumper", "movement_pattern": "Jump", "primary_muscle_group": "Quads/Glutes", "energy_system": "ATP-PC", "cns_load_score": 8.0, "intensity_type": "Power", "recommended_min_sets": 3, "recommended_max_sets": 5, "recommended_min_reps": 3, "recommended_max_reps": 5, "rest_time_seconds_min": 90, "rest_time_seconds_max": 150, "equipment_required": "None", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Intermediate", "injury_risk_level": "Moderate"},
            {"exercise_id": "JMP_005", "exercise_name": "Ankle Bounds", "discipline_category": "Jumper", "movement_pattern": "Jump", "primary_muscle_group": "Calves", "energy_system": "ATP-PC", "cns_load_score": 5.5, "intensity_type": "Power", "recommended_min_sets": 3, "recommended_max_sets": 4, "recommended_min_reps": 10, "recommended_max_reps": 15, "rest_time_seconds_min": 60, "rest_time_seconds_max": 90, "equipment_required": "None", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Intermediate", "injury_risk_level": "Low"},
            # --- THROWER ---
            {"exercise_id": "THR_001", "exercise_name": "Rotational Med Ball Toss", "discipline_category": "Thrower", "movement_pattern": "Throw", "primary_muscle_group": "Obliques", "energy_system": "ATP-PC", "cns_load_score": 6.5, "intensity_type": "Power", "recommended_min_sets": 3, "recommended_max_sets": 6, "recommended_min_reps": 4, "recommended_max_reps": 8, "rest_time_seconds_min": 90, "rest_time_seconds_max": 120, "equipment_required": "Medicine Ball", "unilateral_or_bilateral": "Unilateral", "complexity_level": "Intermediate", "injury_risk_level": "Low"},
            {"exercise_id": "THR_002", "exercise_name": "Standing Power Throws", "discipline_category": "Thrower", "movement_pattern": "Throw", "primary_muscle_group": "Full Body", "energy_system": "ATP-PC", "cns_load_score": 8.5, "intensity_type": "Power", "recommended_min_sets": 4, "recommended_max_sets": 8, "recommended_min_reps": 1, "recommended_max_reps": 3, "rest_time_seconds_min": 180, "rest_time_seconds_max": 240, "equipment_required": "Field", "unilateral_or_bilateral": "Unilateral", "complexity_level": "Advanced", "injury_risk_level": "Moderate"},
            {"exercise_id": "THR_003", "exercise_name": "Barbell Split Jerk", "discipline_category": "Thrower", "movement_pattern": "Push", "primary_muscle_group": "Shoulders", "energy_system": "ATP-PC", "cns_load_score": 9.0, "intensity_type": "Power", "recommended_min_sets": 3, "recommended_max_sets": 6, "recommended_min_reps": 2, "recommended_max_reps": 4, "rest_time_seconds_min": 180, "rest_time_seconds_max": 300, "equipment_required": "Barbell", "unilateral_or_bilateral": "Unilateral", "complexity_level": "Advanced", "injury_risk_level": "High"},
            {"exercise_id": "THR_004", "exercise_name": "Explosive Pushups", "discipline_category": "Thrower", "movement_pattern": "Push", "primary_muscle_group": "Chest/Triceps", "energy_system": "ATP-PC", "cns_load_score": 7.0, "intensity_type": "Power", "recommended_min_sets": 3, "recommended_max_sets": 5, "recommended_min_reps": 5, "recommended_max_reps": 8, "rest_time_seconds_min": 90, "rest_time_seconds_max": 120, "equipment_required": "None", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Intermediate", "injury_risk_level": "Low"},
            {"exercise_id": "THR_005", "exercise_name": "Overhead Keg Toss", "discipline_category": "Thrower", "movement_pattern": "Throw", "primary_muscle_group": "Posterior Chain", "energy_system": "ATP-PC", "cns_load_score": 9.5, "intensity_type": "Power", "recommended_min_sets": 4, "recommended_max_sets": 6, "recommended_min_reps": 2, "recommended_max_reps": 5, "rest_time_seconds_min": 150, "rest_time_seconds_max": 240, "equipment_required": "Medicine Ball", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Advanced", "injury_risk_level": "High"},
            # --- GENERAL ---
            {"exercise_id": "GEN_001", "exercise_name": "Barbell Back Squat", "discipline_category": "General", "movement_pattern": "Squat", "primary_muscle_group": "Quadriceps", "energy_system": "ATP-PC", "cns_load_score": 8.0, "intensity_type": "Strength", "recommended_min_sets": 3, "recommended_max_sets": 6, "recommended_min_reps": 3, "recommended_max_reps": 8, "rest_time_seconds_min": 120, "rest_time_seconds_max": 300, "equipment_required": "Barbell", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Intermediate", "injury_risk_level": "Moderate"},
            {"exercise_id": "GEN_002", "exercise_name": "Romanian Deadlift", "discipline_category": "General", "movement_pattern": "Hinge", "primary_muscle_group": "Hamstrings", "energy_system": "ATP-PC", "cns_load_score": 7.5, "intensity_type": "Strength", "recommended_min_sets": 3, "recommended_max_sets": 5, "recommended_min_reps": 5, "recommended_max_reps": 10, "rest_time_seconds_min": 90, "rest_time_seconds_max": 180, "equipment_required": "Barbell", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Intermediate", "injury_risk_level": "Moderate"},
            {"exercise_id": "GEN_003", "exercise_name": "Bird-Dog Iso Hold", "discipline_category": "General", "movement_pattern": "Core", "primary_muscle_group": "Core", "energy_system": "Oxidative", "cns_load_score": 1.5, "intensity_type": "Recovery", "recommended_min_sets": 2, "recommended_max_sets": 3, "recommended_min_reps": 10, "recommended_max_reps": 15, "rest_time_seconds_min": 30, "rest_time_seconds_max": 60, "equipment_required": "None", "unilateral_or_bilateral": "Unilateral", "complexity_level": "Beginner", "injury_risk_level": "Low"},
            {"exercise_id": "GEN_004", "exercise_name": "Barbell Bench Press", "discipline_category": "General", "movement_pattern": "Push", "primary_muscle_group": "Chest", "energy_system": "ATP-PC", "cns_load_score": 7.0, "intensity_type": "Strength", "recommended_min_sets": 3, "recommended_max_sets": 5, "recommended_min_reps": 5, "recommended_max_reps": 10, "rest_time_seconds_min": 90, "rest_time_seconds_max": 180, "equipment_required": "Barbell", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Intermediate", "injury_risk_level": "Moderate"},
            {"exercise_id": "GEN_005", "exercise_name": "Dumbbell Rows", "discipline_category": "General", "movement_pattern": "Pull", "primary_muscle_group": "Latissimus Dorsi", "energy_system": "ATP-PC", "cns_load_score": 6.0, "intensity_type": "Hypertrophy", "recommended_min_sets": 3, "recommended_max_sets": 4, "recommended_min_reps": 8, "recommended_max_reps": 12, "rest_time_seconds_min": 60, "rest_time_seconds_max": 120, "equipment_required": "Dumbbell", "unilateral_or_bilateral": "Unilateral", "complexity_level": "Beginner", "injury_risk_level": "Low"},
            {"exercise_id": "GEN_006", "exercise_name": "Cable Woodchoppers", "discipline_category": "General", "movement_pattern": "Core", "primary_muscle_group": "Obliques", "energy_system": "Glycolytic", "cns_load_score": 5.0, "intensity_type": "Conditioning", "recommended_min_sets": 3, "recommended_max_sets": 4, "recommended_min_reps": 10, "recommended_max_reps": 15, "rest_time_seconds_min": 60, "rest_time_seconds_max": 90, "equipment_required": "Machine", "unilateral_or_bilateral": "Unilateral", "complexity_level": "Intermediate", "injury_risk_level": "Low"},
            {"exercise_id": "GEN_007", "exercise_name": "Face Pulls", "discipline_category": "General", "movement_pattern": "Pull", "primary_muscle_group": "Rear Deltoids", "energy_system": "Glycolytic", "cns_load_score": 3.0, "intensity_type": "Hypertrophy", "recommended_min_sets": 2, "recommended_max_sets": 4, "recommended_min_reps": 12, "recommended_max_reps": 20, "rest_time_seconds_min": 60, "rest_time_seconds_max": 90, "equipment_required": "Machine", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Beginner", "injury_risk_level": "Low"},
            {"exercise_id": "GEN_008", "exercise_name": "Walking Lunges", "discipline_category": "General", "movement_pattern": "Squat", "primary_muscle_group": "Quadriceps", "energy_system": "Glycolytic", "cns_load_score": 6.5, "intensity_type": "Hypertrophy", "recommended_min_sets": 3, "recommended_max_sets": 4, "recommended_min_reps": 10, "recommended_max_reps": 20, "rest_time_seconds_min": 60, "rest_time_seconds_max": 120, "equipment_required": "Dumbbell", "unilateral_or_bilateral": "Unilateral", "complexity_level": "Intermediate", "injury_risk_level": "Moderate"},
            {"exercise_id": "GEN_009", "exercise_name": "Pull-ups", "discipline_category": "General", "movement_pattern": "Pull", "primary_muscle_group": "Latissimus Dorsi", "energy_system": "ATP-PC", "cns_load_score": 7.5, "intensity_type": "Strength", "recommended_min_sets": 3, "recommended_max_sets": 5, "recommended_min_reps": 5, "recommended_max_reps": 15, "rest_time_seconds_min": 90, "rest_time_seconds_max": 180, "equipment_required": "None", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Intermediate", "injury_risk_level": "Moderate"},
            {"exercise_id": "GEN_010", "exercise_name": "Farmers Carry", "discipline_category": "General", "movement_pattern": "Carry", "primary_muscle_group": "Full Body", "energy_system": "Glycolytic", "cns_load_score": 8.0, "intensity_type": "Conditioning", "recommended_min_sets": 3, "recommended_max_sets": 5, "recommended_min_reps": 20, "recommended_max_reps": 40, "rest_time_seconds_min": 90, "rest_time_seconds_max": 150, "equipment_required": "Dumbbell", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Beginner", "injury_risk_level": "Moderate"},
            {"exercise_id": "GEN_011", "exercise_name": "Bulgarian Split Squat", "discipline_category": "General", "movement_pattern": "Squat", "primary_muscle_group": "Glutes/Quads", "energy_system": "ATP-PC", "cns_load_score": 8.5, "intensity_type": "Strength", "recommended_min_sets": 3, "recommended_max_sets": 5, "recommended_min_reps": 6, "recommended_max_reps": 12, "rest_time_seconds_min": 90, "rest_time_seconds_max": 180, "equipment_required": "Dumbbell", "unilateral_or_bilateral": "Unilateral", "complexity_level": "Advanced", "injury_risk_level": "Moderate"},
            {"exercise_id": "GEN_012", "exercise_name": "Hip Thrusts", "discipline_category": "General", "movement_pattern": "Hinge", "primary_muscle_group": "Glutes", "energy_system": "ATP-PC", "cns_load_score": 7.0, "intensity_type": "Strength", "recommended_min_sets": 3, "recommended_max_sets": 5, "recommended_min_reps": 8, "recommended_max_reps": 15, "rest_time_seconds_min": 90, "rest_time_seconds_max": 150, "equipment_required": "Barbell", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Intermediate", "injury_risk_level": "Low"},
            {"exercise_id": "GEN_013", "exercise_name": "Seated Calf Raises", "discipline_category": "General", "movement_pattern": "Isolation", "primary_muscle_group": "Calves", "energy_system": "Glycolytic", "cns_load_score": 3.0, "intensity_type": "Hypertrophy", "recommended_min_sets": 3, "recommended_max_sets": 5, "recommended_min_reps": 15, "recommended_max_reps": 25, "rest_time_seconds_min": 45, "rest_time_seconds_max": 90, "equipment_required": "Machine", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Beginner", "injury_risk_level": "Low"},
            {"exercise_id": "GEN_014", "exercise_name": "Plank", "discipline_category": "General", "movement_pattern": "Core", "primary_muscle_group": "Core", "energy_system": "Oxidative", "cns_load_score": 4.0, "intensity_type": "Conditioning", "recommended_min_sets": 3, "recommended_max_sets": 5, "recommended_min_reps": 30, "recommended_max_reps": 60, "rest_time_seconds_min": 45, "rest_time_seconds_max": 90, "equipment_required": "None", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Beginner", "injury_risk_level": "Low"},
            {"exercise_id": "GEN_015", "exercise_name": "Deadbug", "discipline_category": "General", "movement_pattern": "Core", "primary_muscle_group": "Core", "energy_system": "Oxidative", "cns_load_score": 2.5, "intensity_type": "Recovery", "recommended_min_sets": 2, "recommended_max_sets": 4, "recommended_min_reps": 10, "recommended_max_reps": 20, "rest_time_seconds_min": 30, "rest_time_seconds_max": 60, "equipment_required": "None", "unilateral_or_bilateral": "Bilateral", "complexity_level": "Beginner", "injury_risk_level": "Low"},
        ]

        # Insert or update exercises
        added_count = 0
        for data in exercises:
            Exercise.objects.update_or_create(
                exercise_id=data['exercise_id'],
                defaults=data
            )
            added_count += 1

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {added_count} exercises.'))
