# Generated by Django 6.0 on 2026-02-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_trainingsession_athlete_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=100)),
                ('discipline_category', models.CharField(choices=[('Runner', 'Runner'), ('Jumper', 'Jumper'), ('Thrower', 'Thrower'), ('General', 'General')], max_length=20)),
                ('movement_pattern', models.CharField(choices=[('Squat', 'Squat'), ('Hinge', 'Hinge'), ('Push', 'Push'), ('Pull', 'Pull'), ('Carry', 'Carry'), ('Sprint', 'Sprint'), ('Jump', 'Jump'), ('Throw', 'Throw'), ('Core', 'Core'), ('Mobility', 'Mobility')], max_length=50)),
                ('primary_muscle_group', models.CharField(max_length=50)),
                ('energy_system', models.CharField(choices=[('ATP-PC', 'ATP-PC'), ('Glycolytic', 'Glycolytic'), ('Oxidative', 'Oxidative')], max_length=20)),
                ('cns_load_score', models.FloatField(help_text='1.0 to 10.0 scale')),
                ('intensity_type', models.CharField(choices=[('Strength', 'Strength'), ('Power', 'Power'), ('Hypertrophy', 'Hypertrophy'), ('Conditioning', 'Conditioning'), ('Recovery', 'Recovery')], max_length=20)),
                ('recommended_min_sets', models.IntegerField(default=1)),
                ('recommended_max_sets', models.IntegerField(default=5)),
                ('recommended_min_reps', models.IntegerField(default=1)),
                ('recommended_max_reps', models.IntegerField(default=20)),
                ('rest_time_seconds_min', models.IntegerField(default=60)),
                ('rest_time_seconds_max', models.IntegerField(default=180)),
                ('equipment_required', models.CharField(choices=[('None', 'None'), ('Barbell', 'Barbell'), ('Dumbbell', 'Dumbbell'), ('Kettlebell', 'Kettlebell'), ('Bands', 'Bands'), ('Machine', 'Machine'), ('Track', 'Track'), ('Field', 'Field'), ('Medicine Ball', 'Medicine Ball')], default='None', max_length=50)),
                ('unilateral_or_bilateral', models.CharField(choices=[('Unilateral', 'Unilateral'), ('Bilateral', 'Bilateral'), ('N/A', 'N/A')], default='Bilateral', max_length=20)),
                ('complexity_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=20)),
                ('injury_risk_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Moderate', max_length=20)),
            ],
        ),
    ]
